CREATE TABLE IF NOT EXISTS ROLE (
  role_id INT NOT NULL AUTO_INCREMENT,
  role_name VARCHAR(255) NOT NULL,
  PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS user (
  user_id INT NOT NULL AUTO_INCREMENT,
  user_name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role_id INT NOT NULL,
  FOREIGN KEY (role_id) REFERENCES ROLE(role_id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (user_id)
);